using System.Collections.Generic;
using System.Text.RegularExpressions;
using Indicium.Schemas;

namespace Indicium
{
    /// <summary>
    /// Abstract type that serves a base class for types generated by the code generator.
    /// </summary>
    public abstract class TokenBase
    {
        public virtual string Identifier { get; }

        public virtual Regex Regex { get; }

        public virtual IEnumerable<Lexeme> Match(string input)
        {
            return default;
        }
    }
}