using System.Text.RegularExpressions;

namespace Indicium
{
    /// <summary>
    /// Abstract type that serves a base class for types generated by the code generator.
    /// </summary>
    public abstract class TokenBase
    {
        public virtual string Id { get; }

        public virtual Regex Regex { get; }

        public virtual TLexeme GetLexeme<TLexeme, TTokenBase>(string value)
            where TTokenBase: TokenBase, new()
            where TLexeme: LexemeBase<TTokenBase>, new()
        {
            var lexeme = new TLexeme();
            return lexeme;
        }
    }
}